CREATE OR REPLACE TABLE `dataform-tutorial-412218.landing.product`
(
  ID STRING,
  NAME STRING,
  MANUFACTURE STRING,
  CREATE_DATE STRING
);

CREATE OR REPLACE TABLE `dataform-tutorial-412218.landing.price`
(
  PRODUCT_ID STRING,
  PRICE STRING,
  START_DATE STRING,
  END_DATE STRING
);