config {
  type: "view",
  name: "product_price_avg",
  schema: "presentation",
  description: "Average prices of product"
}
SELECT 
    p.ID          AS PRODUCT_ID
  , p.NAME        AS PRODUCT_NAME
  , p.MANUFACTURE AS PRODUCT_MANUFACTURE
  , AVG(IFNULL(c.PRICE, 0))       AS AVG_PRODUCT_PRICE
FROM ${ ref("staging", "product") } p
LEFT JOIN ${ ref("staging", "price") } c
  ON p.ID = c.PRODUCT_ID
GROUP BY 
    p.ID
  , p.NAME
  , p.MANUFACTURE  
